Repository tazama-lf/Full-Stack-Docker-Tazama, pull requests merged in 2024-07, with the labels that each got.

#40 feat: Enhancement to the release workflow
  .github/workflows/release.yml
Labels: enhancement

#43 fix: change event-director context
  docker-compose.yaml
Labels: bug

#44 fix: Change url to point to event-directory
  docker-compose.yaml
Labels: bug

#49 fix: update version of arangodb from latest to 3.11.10.1
  docker-compose.yaml
Labels: bug

#50 docs: move optional config step from readme to appendix
  README.md
Labels: documentation
