Repository tazama-lf/Full-Stack-Docker-Tazama, pull requests merged in 2024-10, with the labels that each got.

#69 feat: env/validation
  .env
  docker-compose.dev.logs-base.yaml
  docker-compose.dev.logs-elastic.yaml
  docker-compose.yaml
  env/admin.env
  env/ed.env
  env/event-flow.env
  env/nats-utilities.env
  env/rule-executer.env
  env/tadp.env
  env/tms.env
  env/tp.env
Labels: enhancement

#72 feat: include event-flow in base deployment
  README.md
  arango/migration/local/01-EVENT-FLOW.js
  arango/migration/local/01-SIMPLE.js
  docker-compose.dev.event-flow.yaml
  docker-compose.infrastructure.yaml
  docker-compose.yaml
  start.bat
  start.sh
Labels: enhancement

#73 docs: update test collection for auth and no auth
  README.md
Labels: documentation

#75 fix: update typology config
  arango/migration/local/01-SIMPLE.js
Labels: bug

#74 feat(ui): add ui option to deployment
  arango/migration/local/01-STANDARD.js
  arango/migration/local/02-NO_EVENT_FLOW.js
  docker-compose.dev.ui.yaml
  docker-compose.override.yaml
  start.bat
  start.sh
Labels: enhancement

#76 refactor: apply cache option environment variable split
  env/admin.env
  env/ed.env
  env/event-flow.env
  env/rule-executer.env
  env/tadp.env
  env/tms.env
  env/tp.env
Labels: refactor

#80 fix: windows menu
  start.bat
  start.sh
Labels: bug

#82 docs: update readme
  README.md
  images/full-stack-docker-tazama-start-bat-2.png
Labels: documentation

#83 fix: update env variables
  docker-compose.dev.logs-base.yaml
  env/admin.env
  env/tadp.env
Labels: bug
